<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-NotificationSystem.Worker-62222499-6a92-4ba4-9b2a-1f24a73faf92</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.17" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NotificationSystem.Infrastructure\NotificationSystem.Infrastructure.csproj" />
  </ItemGroup>
</Project>
